module.exports = {
    "netcode": [
        {
            "type": "doc",
            "id": "about"
        },
        {
            type: 'category',
            label: 'Introduction',
            items: ['what-is-netcode', 'who-for', 'the-internet']
        },
        {
            type: 'category',
            label: 'Getting Started',
            items: [
                {
                    type: 'category',
                    label: 'Installation',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'installation'
                        }
                    ]
                },
                'tutorials/get-started-ngo',
            ]
        },
        {
            type: 'category',
            label: 'In-game Multiplayer',
            items: [
                
            ]
        },
        {
            type: 'category',
            label: 'Going Live',
            items: [
                
            ]
        },
        {
            type: 'category',
            label: 'Optimizations',
            items: [
                
            ]
        },
        {
            type: 'category',
            label: 'Troubleshooting',
            items: [
                
            ]
        },
        {
            type: 'category',
            label: 'Samples',
            items: [
                {
                    type:'category',
                    label: 'Bitesize',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'learn/bitesize'
                        },
                    ]
                },
                {
                    type:'category',
                    label: 'Boss Room',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'learn/bossroom'
                        },
                    ]
                },
                {
                    type:'category',
                    label: 'Codemonkey',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'learn/codemonkey'
                        },
                    ]
                },
                {
                    type:'category',
                    label: 'Dapper',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'learn/dapper'
                        },
                    ]
                },
                {
                    type:'category',
                    label: 'Dilmer',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'learn/dilmer'
                        },
                    ]
                },
            ]
        },
    ],

    Multiplayer:
        [
            {
                "type": "doc",
                "id": "reference/glossary/high-level-terminology"
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Lag",
                "items": [
                    {
                        "type": "doc",
                        "id": "reference/glossary/ticks-and-update-rates"
                    },
                    {
                        "type": "doc",
                        "id": "learn/lagandpacketloss"
                    },
                    {
                        "type": "doc",
                        "id": "learn/clientside_interpolation"
                    },
                    {
                        "type": "doc",
                        "id": "learn/dealing-with-latency"
                    },
                        ],
            },
            {
                "type": "doc",
                "id": "reference/glossary/network-terms"
            },
            {
                "type": "doc",
                "id": "reference/glossary/prioritization"
            },
            {
                "type": "doc",
                "id": "reference/glossary/relevancy"
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Multiplayer Game Architecture",
                "items": [
                    {
                        "type": "doc",
                        "id": "learn/multiplayer-game-arhitecture"
                    },
                    {
                        "type": "doc",
                        "id": "reference/glossary/network-topologies"
                    },
                    {
                        "type": "doc",
                        "id": "learn/listen-server-host-architecture"
                    }
                        ]
            },
            {
                "type": "doc",
                "id": "learn/faq"
            },
            {
                "type": "doc",
                "id": "reference/dedicated-server"
            },
        ],

    api:
        [
            {
                "type": "doc",
                "id": "api/introduction"
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Netcode",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode",
                        "label": "Netcode APIs",
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.INetworkUpdateSystem",
                        "label": "INetworkUpdateSystem"
                    },

                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkBehaviour",
                        "label": "NetworkBehaviour"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkBehaviourUpdater",
                        "label": "NetworkBehaviourUpdater"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkObjectReference",
                        "label": "NetworkObjectReference"
                    },

                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkObject.SpawnDelegate",
                        "label": "SpawnDelegate"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkObject.VisibilityDelegate",
                        "label": "VisibilityDelegate"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkTickSystem",
                        "label": "NetworkTickSystem"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkUpdateLoop",
                        "label": "NetworkUpdateLoop"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkUpdateStage",
                        "label": "NetworkUpdateStage"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.INetworkPrefabInstanceHandler",
                        "label": "INetworkPrefabInstanceHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkPrefab",
                        "label": "NetworkPrefab"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkPrefabs",
                        "label": "NetworkPrefabs"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkPrefabOverride",
                        "label": "NetworkPrefabOverride"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkPrefabsList",
                        "label": "NetworkPrefabsList"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkDelivery",
                        "label": "NetworkDelivery"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkEvent",
                        "label": "NetworkEvent"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkPrefabHandler",
                        "label": "NetworkPrefabHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.BitCounter",
                        "label": "BitCounter"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.BitReader",
                        "label": "BitReader"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.BitWriter",
                        "label": "BitWriter"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.BufferSerializer-1",
                        "label": "BufferSerializer-1"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.BytePacker",
                        "label": "BytePacker"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ByteUnpacker",
                        "label": "ByteUnpacker"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferReader",
                        "label": "FastBufferReader"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferWriter.ForEnums",
                        "label": "FastBufferWriter.ForEnums"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferWriter.ForFixedStrings",
                        "label": "FastBufferWriter.ForFixedStrings"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferWriter.ForNetworkSerializable",
                        "label": "FastBufferWriter.ForNetworkSerializable"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferWriter.ForPrimitives",
                        "label": "FastBufferWriter.ForPrimitives"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferWriter.ForStructs",
                        "label": "FastBufferWriter.ForStructs"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.FastBufferWriter",
                        "label": "FastBufferWriter"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.INetworkSerializeByMemcpy",
                        "label": "INetworkSerializeByMemcpy"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ForceNetworkSerializeByMemcpy-1",
                        "label": "ForceNetworkSerializeByMemcpy-1"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariableWritePermission",
                        "label": "NetworkVariableWritePermission"
                    },
                ],
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Time",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkTime",
                        "label": "NetworkTime"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkTimeSystem",
                        "label": "NetworkTimeSystem"
                    },
                ],
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Configuration",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.HashSize",
                        "label": "HashSize"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkConfig",
                        "label": "NetworkConfig"
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Connection",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkClient",
                        "label": "NetworkClient"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.PendingClient",
                        "label": "PendingClient"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.PendingClient.State",
                        "label": "PendingClient.State"
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Exceptions",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.InvalidChannelException",
                        "label": "InvalidChannelException"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.InvalidParentException",
                        "label": "InvalidParentException"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkConfigurationException",
                        "label": "NetworkConfigurationException"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NotListeningException",
                        "label": "NotListeningException"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NotServerException",
                        "label": "NotServerException"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.SpawnStateException",
                        "label": "SpawnStateException"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.VisibilityChangeException",
                        "label": "VisibilityChangeException"
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Logging",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.LogLevel",
                        "label": "LogLevel"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkLog",
                        "label": "NetworkLog"
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Messaging",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ClientRpcAttribute",
                        "label": "ClientRpcAttribute"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ClientRpcParams",
                        "label": "ClientRpcParams"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ClientRpcReceiveParams",
                        "label": "ClientRpcReceiveParams"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ClientRpcSendParams",
                        "label": "ClientRpcSendParams"
                    },
                    {
                        "collapsed": true,
                        "type": "category",
                        "label": "CustomMessagingManager",
                        "items": [
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.CustomMessagingManager",
                                "label": "CustomMessagingManager"
                            },
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.CustomMessagingManager.HandleNamedMessageDelegate",
                                "label": "HandleNamedMessageDelegate"
                            },
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.CustomMessagingManager.UnnamedMessageDelegate",
                                "label": "UnnamedMessageDelegate"
                            }
                        ]
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.RpcAttribute",
                        "label": "RpcAttribute"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.RpcDelivery",
                        "label": "RpcDelivery"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ServerRpcAttribute",
                        "label": "ServerRpcAttribute"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ServerRpcParams",
                        "label": "ServerRpcParams"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ServerRpcReceiveParams",
                        "label": "ServerRpcReceiveParams"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.ServerRpcSendParams",
                        "label": "ServerRpcSendParams"
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "NetworkManager",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkManager",
                        "label": "NetworkManager"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkManager.ConnectionApprovalRequest",
                        "label": "ConnectionApprovalRequest"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkManager.ConnectionApprovalResponse",
                        "label": "ConnectionApprovalResponse"
                    },
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "NetworkVariable",
                "items": [

                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariableBase",
                        "label": "NetworkVariableBase"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariable-1",
                        "label": "NetworkVariable-1"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariable-1.OnValueChangedDelegate",
                        "label": "OnValueChangedDelegate"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariableReadPermission",
                        "label": "NetworkVariableReadPermission"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.UserNetworkVariableSerialization-1",
                        "label": "UserNetworkVariableSerialization-1"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariableSerializationTypes",
                        "label": "NetworkVariableSerializationTypes"
                    },
                ],
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "NetworkList-1",
                "items": [
                    {
                        "collapsed": true,
                        "type": "category",
                        "label": "NetworkList-1",
                        "items": [
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.NetworkList-1",
                                "label": "NetworkList-1"
                            },
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.NetworkList-1.OnListChangedDelegate",
                                "label": "OnListChangedDelegate"
                            }
                        ]
                    },
                    {
                        "collapsed": true,
                        "type": "category",
                        "label": "NetworkListEvent-1",
                        "items": [
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.NetworkListEvent-1",
                                "label": "NetworkListEvent-1"
                            },
                            {
                                "type": "doc",
                                "id": "api/Unity.Netcode.NetworkListEvent-1.EventType",
                                "label": "EventType"
                            }
                        ]
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "SceneEvent",
                "items": [

                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.SceneEvent",
                        "label": "SceneEvent"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.SceneEventProgressStatus",
                        "label": "SceneEventProgressStatus"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.SceneEventType",
                        "label": "SceneEventType"
                    },
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "SceneManagement",
                "items": [

                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager",
                        "label": "NetworkSceneManager"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.SceneEventDelegate",
                        "label": "SceneEventDelegate"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.VerifySceneBeforeLoadingDelegateHandler",
                        "label": "VerifySceneBeforeLoadingDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnEventCompletedDelegateHandler",
                        "label": "OnEventCompletedDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnLoadCompleteDelegateHandler",
                        "label": "OnLoadCompleteDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnLoadDelegateHandler",
                        "label": "OnLoadDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnSynchronizeCompleteDelegateHandler",
                        "label": "OnSynchronizeCompleteDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnSynchronizeDelegateHandler",
                        "label": "OnSynchronizeDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnUnloadCompleteDelegateHandler",
                        "label": "OnUnloadCompleteDelegateHandler"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSceneManager.OnUnloadDelegateHandler",
                        "label": "OnUnloadDelegateHandler"
                    },
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Serialization",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Arithmetic",
                        "label": "Arithmetic"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.INetworkSerializable",
                        "label": "INetworkSerializable"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkVariableSerializationTypes",
                        "label": "NetworkVariableSerializationTypes"
                    },
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Spawning",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkSpawnManager",
                        "label": "NetworkSpawnManager"
                    }
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "NetworkTransport",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.NetworkTransport",
                        "label": "NetworkTransport"
                    },
                ]
            },
            {
                "collapsed": true,
                "type": "category",
                "label": "Transports.UTP",
                "items": [
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.ErrorUtilities",
                        "label": "Transports.UTP.ErrorUtilities"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.SecretsLoaderHelper",
                        "label": "Transports.UTP.SecretsLoaderHelper"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.INetworkStreamDriverConstructor",
                        "label": "Transports.UTP.INetworkStreamDriverConstructor"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP",
                        "label": "Transports.UTP"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.NetworkMetricsContext",
                        "label": "Transports.UTP.NetworkMetricsContext"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.UnityTransport.ConnectionAddressData",
                        "label": "Transports.UTP.UnityTransport.ConnectionAddressData"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.UnityTransport",
                        "label": "Transports.UTP.UnityTransport"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.UnityTransport.ProtocolType",
                        "label": "Transports.UTP.UnityTransport.ProtocolType"
                    },
                    {
                        "type": "doc",
                        "id": "api/Unity.Netcode.Transports.UTP.UnityTransport.SimulatorParameters",
                        "label": "Transports.UTP.UnityTransport.SimulatorParameters"
                    },
                ]
            },
        ]
}
